java_library(
  name = 'closure-stylesheets',
  srcs = glob(includes=['src/**/*.java']) + [':javacc'],
  deps = [
    '//third-party:COMPILE',
    ':javacc',
  ],
  visibility = [
    'PUBLIC',
  ],
)

genrule(
  name = 'javacc',
  srcs = [
    'gen_parser.sh',
    'lib/javacc.jar',
    'src/com/google/common/css/compiler/ast/GssParserCC.jj',
  ],
  cmd = '$SRCS $OUT $TMP',
  out = 'parser.src.zip',
)
