java_library(
  name = 'closure-stylesheets',
  srcs = glob(includes=['src/**/*.java']) + [':javacc'],
  resources_root = '.',
  annotation_processors = [
    'com.google.auto.value.processor.AutoAnnotationProcessor',
    'com.google.auto.value.processor.AutoValueProcessor',
  ],
  annotation_processor_deps = ['//closure/closure-templates:auto-value'],
  deps = [
    '//closure/closure-compiler:closure-compiler',
    '//closure/closure-templates:auto-value',
    '//closure/closure-compiler:args4j',
    '//closure/closure-compiler:gson',
    '//closure/closure-compiler:guava',
    ':javacc',
    '//closure/closure-compiler:jsr305',
  ],
  visibility = [
    'PUBLIC',
  ],
)

genrule(
  name = 'javacc',
  srcs = [
    'gen_parser.sh',
    'lib/javacc.jar',
    'src/com/google/common/css/compiler/ast/GssParserCC.jj',
  ],
  cmd = '$SRCS $OUT $TMP',
  out = 'parser.src.zip',
)
